// Generated by CoffeeScript 1.6.3
var SweetJSCompiler, sjs;

sjs = require('sweet.js');

SweetJSCompiler = (function() {
  SweetJSCompiler.prototype.brunchPlugin = true;

  SweetJSCompiler.prototype.type = 'javascript';

  SweetJSCompiler.prototype.extension = 'sjs';

  function SweetJSCompiler(cfg) {
    null;
  }

  SweetJSCompiler.prototype.compile = function(data, path, callback) {
    var err, error, result;
    try {
      return result = sjs.compile(data);
    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, result.code);
    }
  };

  return SweetJSCompiler;

})();

module.exports = SweetJSCompiler;
